# Generated by Django 5.0.7 on 2024-08-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rfid_tag', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('rack_location', models.CharField(max_length=100)),
            ],
        ),
    ]
