# Generated by Django 5.0.7 on 2024-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='rack_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='medicine',
            name='original_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='rfid_tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
